version: '3.9'

networks:
  my-network:
x-app-volume:
  &app-volume  # i don't know why, but it works ;)
  type: bind
  source: ./room
  target: /app

services:
  app:
    networks:
      - my-network
    ports:
      - 8080:8080
    depends_on:
      - database
    restart: "always"
    volumes:
      - *app-volume
    build: .

  database:
    networks:
      - my-network
    ports:
      - 3306:3306
    image: mariadb
    restart: always
    volumes:
      - *app-volume
    environment:
      MYSQL_ROOT_PASSWORD: "groot"
    command: --init_file /app/database/init.sql

  phpmyadmin:
      networks:
        - my-network
      ports:
        - 8088:80
      depends_on:
        - database
      image: phpmyadmin/phpmyadmin
      restart: always
      environment:
        PMA_HOST: database
        PMA_ARBITRARY: 1
        MYSQL_ROOT_PASSWORD: groot
